api_version = "2025-10"

[[extensions]]
name = "t:name"
description = "t:description"
handle = "bundlestack-discount"
uid = "5bec24e8-7604-40d1-a2d5-4c74355a76bd"
type = "function"

[[extensions.targeting]]
target = "cart.lines.discounts.generate.run"
input_query = "src/cart_lines_discounts_generate_run.graphql"
export = "cart-lines-discounts-generate-run"

[[extensions.targeting]]
target = "cart.delivery-options.discounts.generate.run"
input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
export = "cart-delivery-options-discounts-generate-run"

[extensions.build]
command = ""
path = "dist/function.wasm"

[extensions.ui.paths]
create = "/app/promotions/bogo/new"
details = "/app/promotions/bogo/:id"
