# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4aade1f433c3c5bd867c99cce348cede"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "BundleStack"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products,write_discounts,read_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[app_proxy]
url = "/app-proxy"
subpath = "bundlestack"
prefix = "apps"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
