# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4aade1f433c3c5bd867c99cce348cede"
name = "BundleStack"
application_url = "https://bundlestack-pfee.onrender.com"
embedded = true
handle = "bundlestack"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://bundlestack-pfee.onrender.com/auth/callback",
  "https://bundlestack-pfee.onrender.com/auth/shopify/callback"
]

[app_proxy]
url = "https://bundlestack-pfee.onrender.com/app-proxy"
subpath = "bundlestack"
prefix = "apps"
